### ISSUE TITLE
Attach a onClick event on button

### ISSUE THREAD

**Issue by GautierT** [CherryProjects/react-facebook#27]
Hi, 
I would like to be able to track when an user click on the share button.
```
<FacebookProvider appID="xxxxx">
    <Share href="https://www.facebook.com/xxxxxx">
        <Button color='facebook'
                onClick={() => {
                    console.log('share');
                    ReactGA.event({
                        category: 'Facebook',
                        action: 'Share',
                        label: 'Label'
                    });
                }}>
            <Icon name='facebook'/> Partager
        </Button>
    </Share>
</FacebookProvider>
```

This doesn't work. Thanks !

**Comment by seeden** [comment]
I will try to fix it today.
Anyway I am going to integrate this library with [react-g-analytics](https://github.com/seeden/react-g-analytics) because I want to use it in same way automatically

**Comment by GautierT** [comment]
Awesome ! Thanks ! 
I will look into https://github.com/seeden/react-g-analytics.

**Comment by seeden** [comment]
You example will work in the new release

**Comment by GautierT** [comment]
Tested! Thanks !

**Comment by bjackson** [comment]
How can I get this to work with the Like button?
