### ISSUE TITLE
How change default locale?

### ISSUE THREAD

**Issue by BrunoQuaresma** [CherryProjects/react-facebook#28]

**Comment by seeden** [comment]
Hi @BrunoQuaresma 

Use 
```js
<FacebookProvider language="en_US">
   your components
</FacebookProvider>
```

**Comment by konekoya** [comment]
Hi @seeden,

It's not working even you set the language props on `FacebookProvider`
And as I inspected the page source, the locale for my like button is still set as `locale=en_US`.
Have I missed something?

Thanks!

**Comment by seeden** [comment]
Do you have just one FacebookProvider for whole application?

**Comment by konekoya** [comment]
Hi @seeden,

Nope, I have two. One for like and one for share.
It's actually working now. Do you mind for a PR to document language prop and like button layout prop?

**Comment by seeden** [comment]
Can you use just one instance of FacebookProvider for whole project? You can add it before your Router.
