### ISSUE TITLE
Share Button Callback

### ISSUE THREAD

**Issue by amorino** [CherryProjects/react-facebook#29]
I searched the component of Share Button and Share and I couldn't find the callback method after the link is shared.

**Comment by seeden** [comment]
PR will be welcome

**Comment by seeden** [comment]
Share and Feed components now support event like onResponse, onError and onReady

**Comment by lampt2010** [comment]
<FacebookProvider appId="key">
          <Share href="http://www.facebook.com"  onResponse={this.handleResponse} onError={this.handleError}>
            {({ handleClick, loading,error,data }) => (
              <button type="button" disabled={loading} onClick={handleClick} >Share</button>
            )}
          </Share>
///////////
 handleResponse = (data) => {
    debugger
    alert('bog');
  }



when i click share success not call to handleResponse . Y can demo help me ?

**Comment by nbudinov** [comment]
onResponse, onError and onReady do not work with Share button.

Please help here, gotta make it work :/

**Comment by lampt2010** [comment]
> `handleClick = (caption) => {
        var hours = 24; // Reset when storage is more than 24hours
        var now = new Date().getTime();
        var setupTime = localStorage.getItem('setupTime');
        if ((now - setupTime > hours * 60 * 60 * 1000) || !setupTime) {
            localStorage.removeItem('CURRENT_USER');
            localStorage.removeItem('setupTime');
            this.props.actShowLoginFb();
        } else {
            //SDK loaded, initialize it
            window.FB.init({
                appId: AppConstants.FACEBOOK_APPID,
                xfbml: true,
                version: 'v2.6'
            });
            const props = this.props.item;
            const th = this;
            //JS SDK initialized, now you can use it
            window.FB.ui({
                method: 'share',
                title: 'Title Goes here',
                description: '. ',
                href: caption,
            },
                function (response) {
                    if (response && !response.error_code) {
                        th.props.actSharedSuccess(props.id).then(() => {
                        });
                    } else {
                    }
                });
            //load the JavaScript SDK
            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) { return; }
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/en_US/sdk.js";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        }
    }`

> 

>this my code resolve this response from sharing but it doesn't display image and title share because my project is client side
