### ISSUE TITLE
React.PropTypes Deprecated in latest version of react

### ISSUE THREAD

**Issue by finbarmaginn** [CherryProjects/react-facebook#33]
getting the following error in my console

`Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

[https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

**Comment by seeden** [comment]
fixed in the latest release
