### ISSUE TITLE
Facebook post embed unmount when switch route with react-router

### ISSUE THREAD

**Issue by joevo2** [CherryProjects/react-facebook#34]
The facebook embeds load slow initially, which can be understand but every time i switch route the post unmount and reload even though other content doesn't.

**Comment by seeden** [comment]
Hi @joevo2. Embedded component is using

```js
shouldComponentUpdate() {
    return false;
  }
```

If you are on the same route our components are not reloaded.
We are not using any cache for DOM nodes in this moment.
