### ISSUE TITLE
How to know when iframe element was appended

### ISSUE THREAD

**Issue by Flave** [CherryProjects/react-facebook#37]
Hi,

I'm trying to get the height of a rendered Facebook Post. In order to do that I want to attach an `iframe.onload` event listener. It seems though as if the iframe is not appended immediately. Inside componentDidMount it isn't possible yet to grab the iframe.

```
  componentDidMount() {
      // no iframe is being found here
      $(this.root).find('iframe').on('load', function() {
        console.log(this.root.clientHeight);
      }.bind(this));
  }

  render() {
    return (
      <div ref={(root) => this.root = root} className="feed__item">
        <FacebookProvider appId="1754125368233773">
          <EmbeddedPost href={this.props.url} width="400" />
        </FacebookProvider>
      </div>
    );
  }
```

Is there a way to actually achieve this?

**Comment by seeden** [comment]
I will add onReady event.

**Comment by seeden** [comment]
I added onParse event.

**Comment by Flave** [comment]
Awesome! Thanks a lot :)

**Comment by iethem** [comment]
Is there a way to add a loading spinner for Facebook Embed?

**Comment by kevinqiu92** [comment]
@Flave were you able to get this callback to work? I tried using both `onReady` and `onParse` and it doesn't seem to be called.
