### ISSUE TITLE
Rerender when props are updated

### ISSUE THREAD

**Issue by hughbe** [CherryProjects/react-facebook#39]
I have the following code:

```jsx
<FacebookProvider appId={this.props.appId}>
    <EmbeddedPost className="embedded-post" href={this.props.permalink_url} />
</FacebookProvider>
```

However, when `this.props.permalink_url` updates, the post does not update.

It would be nice if the post reloads if the `href` prop updates

**Comment by hughbe** [comment]
For the record the workaround is:

```jsx
<FacebookProvider key={this.props.permalink_url} appId={this.props.appId}>
    <EmbeddedPost className="embedded-post" href={this.props.permalink_url} />
</FacebookProvider>
```

**Comment by seeden** [comment]
Hi @hughbe I see the issue in the Parser. I will try to fix it today

**Comment by hughbe** [comment]
Awesome, thanks for the quick diagnosis

**Comment by seeden** [comment]
I will release a new version on Monday. Sorry for the delay

**Comment by seeden** [comment]
fixed in the latest release

**Comment by aditya1994** [comment]
Some posts are not being rendered by FacebookProvider

`FacebookProvider appId="394445311100528" >{this.createFbList(this.state.face)}</FacebookProvider>

createFbList = (listVar) => {
    let l = []
    if(listVar != null && listVar.length > 0){
      for (let i = 0; i< listVar.length; i++){
        if(listVar[i][0] == '/')
          listVar[i] = 'www.facebook.com' + listVar[i];
        l.push(<li key  = {i} style={{'marginBottom' : '2vh'}} >
        <EmbeddedPost href={listVar[i]}/></li>);
      }
    }
    return l;
  };`

Is it might be because of the appID or is there some problem in rendering? The post is visible on the website
