### ISSUE TITLE
Uncaught (in promise) Error: You need to set appId

### ISSUE THREAD

**Issue by nickbae91** [CherryProjects/react-facebook#40]
Hi,

After upgrading react-facebook to the latest version (^4.0.8), I start getting this error:

"Uncaught (in promise) Error: You need to set appId"

This worked just fine before the upgrade, with the following implementation code:

`<FacebookProvider appID="1679023659038468">
              <Like href="https://facebook.com/sagepathio" colorScheme="dark" size='large' showFaces={true} width={190} />
            </FacebookProvider>`

What could be wrong? I suspect it's a bug that made its way in during the upgrades, or even potentially dependency-related. Please let me know if you require more information.

**Comment by seeden** [comment]
Hi @nickbae91 . Please use appId instead of appID

**Comment by nickbae91** [comment]
That worked perfectly. Thanks for that!!

**Comment by seeden** [comment]
you are welcome
